name: Build and Push Docker Images

on: 
  push:
    branches:
      - main
    paths:
      - 'mom_ubuntu.dockerfile'
      - 'pySurfMod.dockerfile'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      mom_ubuntu_changed: ${{ steps.check-mom-ubuntu.outputs.changed }}
      pysurfmod_changed: ${{ steps.check-pysurfmod.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: check-mom-ubuntu
        run: |
          CHANGED=$(git diff --name-only HEAD~1 HEAD | grep '^mom_ubuntu.dockerfile$' || true)
          if [[ -z "$CHANGED" ]]; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - id: check-pysurfmod
        run: |
          CHANGED=$(git diff --name-only HEAD~1 HEAD | grep '^pySurfMod.dockerfile$' || true)
          if [[ -z "$CHANGED" ]]; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

  build_mom_ubuntu:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.mom_ubuntu_changed == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push mom_ubuntu image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./mom_ubuntu.dockerfile
        push: true
        tags: svchb/mom_ubuntu:latest

  build_pySurfMod:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.pysurfmod_changed == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push pySurfMod image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./pySurfMod.dockerfile
        push: true
        tags: svchb/surface_science_mom:latest
