name: Build and Push Docker Images

on: 
  push:
    branches:
      - main
    paths:
      - 'mom_ubuntu.dockerfile'
      - 'pySurfMod.dockerfile'

jobs:
  build_mom_ubuntu:
    runs-on: ubuntu-latest
    if: contains(github.event.compare, 'mom_ubuntu.dockerfile')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push mom_ubuntu image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./mom_ubuntu.dockerfile
        push: true
        tags: svchb/mom_ubuntu:latest

  build_pySurfMod:
    needs: build_mom_ubuntu
    runs-on: ubuntu-latest
    if: contains(github.event.compare, 'pySurfMod.dockerfile')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push pySurfMod image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./pySurfMod.dockerfile
        push: true
        tags: svchb/surface_science_mom:latest
