name: Build and Push Docker Images

on: 
  push:
    branches:
      - main
    paths:
      - 'mom_ubuntu.dockerfile'
      - 'pySurfMod.dockerfile'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      mom_ubuntu_changed: ${{ steps.check-mom-ubuntu.outputs.changed }}
      pysurfmod_changed: ${{ steps.check-pysurfmod.outputs.changed }}
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
  
      - id: check-mom-ubuntu
        run: |
          echo "::set-output name=changed::false"  # Default value
          if git diff --name-only HEAD~1 HEAD | grep -q 'mom_ubuntu.dockerfile'; then
            echo "::set-output name=changed::true"
          fi
  
      - id: check-pysurfmod
        run: |
          echo "::set-output name=changed::false"  # Default value
          if git diff --name-only HEAD~1 HEAD | grep -q 'pySurfMod.dockerfile'; then
            echo "::set-output name=changed::true"
          fi


  build_mom_ubuntu:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.mom_ubuntu_changed == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push mom_ubuntu image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./mom_ubuntu.dockerfile
        push: true
        tags: svchb/mom_ubuntu:latest, svchb/mom_ubtuntu:u20.04, svchb/mom_ubuntu:v1

  build_pySurfMod:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.pysurfmod_changed == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push pySurfMod image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./pySurfMod.dockerfile
        push: true
        tags: svchb/surface_science_mom:latest, svchb/surface_science_mom:u20.04, svchb/surface_science_mom:v1
